name: Release

on:
  workflow_dispatch

jobs:
  setup:
    name: Setup
    uses: tlslink/sslcon/.github/workflows/release-setup.yml@main
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.build == 'macos-arm64' }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images#available-images
        build: [linux-latest, linux, linux-arm64, windows, macos-arm64]
        include:
        - build: linux-latest
          os: ubuntu-24.04
          qt: 6.11.1
          arch: linux_gcc_64
          qt-modules: 'qtwebsockets'
          installer-name: anylink-client-linux-amd64.run
        - build: linux
          os: ubuntu-22.04
          qt: 6.11.1
          arch: linux_gcc_64
          qt-modules: 'qtwebsockets'
          installer-name: anylink-client-linux-amd64.run
        - build: linux-arm64
          os: ubuntu-24.04-arm
          qt: 6.11.1
          arch: linux_gcc_arm64
          qt-modules: 'qtwebsockets'
          installer-name: anylink-client-linux-arm64.run
        - build: windows
          os: windows-2022
          qt: 6.11.1
          arch: win64_msvc2022_64
          qt-modules: 'qtwebsockets'
          qt-tools: 'tools_qtcreator_gui'
          installer-name: anylink-client-windows10-amd64.exe
        - build: macos-arm64
          os: macos-14
          qt: 6.11.1
          arch: clang_64
          qt-modules: 'qtwebsockets'
          installer-name: anylink-client-installer
    steps:
    - if: startsWith(github.ref, 'refs/heads/')
      shell: bash
      run: |
        if [ "${{ matrix.build }}" = "linux-latest" ]; then
          echo "ARCHIVE_NAME=anylink-client-linux_latest-amd64.tar.gz" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "linux" ]; then
          echo "ARCHIVE_NAME=anylink-client-linux-amd64.tar.gz" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "linux-arm64" ]; then
          echo "ARCHIVE_NAME=anylink-client-linux-arm64.tar.gz" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "windows" ]; then
          echo "ARCHIVE=anylink-client-windows10-amd64" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=anylink-client-windows10-amd64.zip" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "macos-arm64" ]; then
          echo "ARCHIVE_NAME=anylink-client-macOS-arm64.dmg" >> $GITHUB_ENV
        fi
    - if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        if [ "${{ matrix.build }}" = "linux-latest" ]; then
          echo "ARCHIVE_NAME=anylink-client-${{ github.ref_name }}-linux_latest-amd64.tar.gz" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "linux" ]; then
          echo "ARCHIVE_NAME=anylink-client-${{ github.ref_name }}-linux-amd64.tar.gz" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "linux-arm64" ]; then
          echo "ARCHIVE_NAME=anylink-client-${{ github.ref_name }}-linux-arm64.tar.gz" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "windows" ]; then
          echo "ARCHIVE=anylink-client-${{ github.ref_name }}-windows10-amd64" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=anylink-client-${{ github.ref_name }}-windows10-amd64.zip" >> $GITHUB_ENV
        elif [ "${{ matrix.build }}" = "macos-arm64" ]; then
          echo "ARCHIVE_NAME=anylink-client-${{ github.ref_name }}-macOS-arm64.dmg" >> $GITHUB_ENV
        fi
    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == ubuntu* ]]; then
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q --force-yes \
          automake cmake git wget libfuse2 desktop-file-utils tree \
          build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev \
          libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 \
          libxcb-xinerama0 libxcb-composite0 libxcb-cursor0 libxcb-damage0 \
          libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0 \
          libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 \
          libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 \
          libxkbcommon-x11-dev extra-cmake-modules libsecret-1-dev
        fi
    - if: matrix.build == 'macos-arm64'
      name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v7
      with: 
        p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
    - if: matrix.build == 'windows'
      name: Setup msvc
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
    - name: Install Qt
      # https://github.com/jurplel/install-qt-action
      uses: jurplel/install-qt-action@v4
      with:
        arch: ${{ matrix.arch }}
        version: ${{ matrix.qt }} # https://download.qt.io/online/qtsdkrepository/
        modules: ${{ matrix.qt-modules }}
        tools: ${{ matrix.qt-tools }}
        install-deps: false
        cache: false
        cache-key-prefix: 'cache-qt'
        extra: '--base https://mirrors.ocf.berkeley.edu/qt'  # https://download.qt.io/static/mirrorlist/
        aqtsource: 'git+https://github.com/miurahr/aqtinstall.git'
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build
      shell: bash
      run: |
        if [[ "${{ matrix.build }}" == linux* ]]; then
          qmake
          make -j $(nproc)
        elif [[ "${{ matrix.build }}" == "windows" ]]; then
          rm "C:\Program Files\Git\usr\bin\link.exe"
          qmake
          "${IQTA_TOOLS}/QtCreator/bin/jom/jom.exe" -j $(nproc) -f Makefile.Release
        elif [[ "${{ matrix.build }}" == "macos-arm64" ]]; then
          qmake
          make -j $(sysctl -n hw.logicalcpu)
        fi

    - name: Build archive
      shell: bash
      run: |
        echo $PATH
        mkdir archive
        # ls -lR
        if [ "${{ matrix.build }}" = "linux" -o "${{ matrix.build }}" = "linux-latest"  ]; then
          # probonopd
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage out/opt/anylink/bin/anylink -extra-plugins=platformthemes/libqgtk3.so -no-copy-copyright-files -no-translations -unsupported-allow-new-glibc
          wget -c -nv https://github.com/tlslink/sslcon/releases/download/latest/sslcon-linux-amd64.tar.gz
          tar -zxvf sslcon-*.tar.gz
          cp vpnagent sslcon out/opt/anylink/bin
          7z a installer/packages/root/data/anylink.7z ./out/opt/anylink/*
          cd installer
          rm -fr packages/maintenance
          wget -c -nv https://download.qt.io/online/qtsdkrepository/linux_x64/ifw/tools_ifw_411/qt.tools.ifw.411/4.11.0-0-202603231357ifw-linux-x64.7z
          7z x -y 4.11*.7z
          ./bin/binarycreator --offline-only -c config/config.xml -p packages ${{ matrix.installer-name }}
          chmod +x ./*.run
          tar -zcvf "${{ github.workspace }}"/archive/${{ env.ARCHIVE_NAME }} ${{ matrix.installer-name }}
        elif [ "${{ matrix.build }}" = "linux-arm64" ]; then
          # probonopd
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-aarch64.AppImage"
          chmod a+x linuxdeployqt-continuous-aarch64.AppImage
          ./linuxdeployqt-continuous-aarch64.AppImage out/opt/anylink/bin/anylink -extra-plugins=platformthemes/libqgtk3.so -no-copy-copyright-files -no-translations -unsupported-allow-new-glibc
          wget -c -nv https://github.com/tlslink/sslcon/releases/download/latest/sslcon-linux-arm64.tar.gz
          tar -zxvf sslcon-*.tar.gz
          cp vpnagent sslcon out/opt/anylink/bin
          7z a installer/packages/root/data/anylink.7z ./out/opt/anylink/*
          cd installer
          rm -fr packages/maintenance
          wget -c -nv https://download.qt.io/online/qtsdkrepository/linux_arm64/ifw/tools_ifw_411/qt.tools.ifw.411/4.11.0-0-202603231357ifw-linux-arm64.7z
          7z x -y 4.11*.7z
          ./bin/binarycreator --offline-only -c config/config.xml -p packages ${{ matrix.installer-name }}
          chmod +x ./*.run
          tar -zcvf "${{ github.workspace }}"/archive/${{ env.ARCHIVE_NAME }} ${{ matrix.installer-name }}
        elif [ "${{ matrix.build }}" = "windows" ]; then
          windeployqt out/bin/anylink.exe --no-translations --no-system-d3d-compiler --no-opengl-sw --no-svg
          curl -k -L -O https://github.com/tlslink/sslcon/releases/download/latest/sslcon-windows10-amd64.7z
          7z x -y sslcon-*.7z
          cp vpnagent.exe sslcon.exe wintun.dll out/bin
          7z a installer/packages/root/data/anylink.7z ./out/bin/*
          cd installer
          rm -fr packages/maintenance
          curl -k -O -L https://download.qt.io/online/qtsdkrepository/windows_x86/ifw/tools_ifw_49/qt.tools.ifw.49/4.9.0-0-202503040800ifw-win-x64.7z
          7z x -y 4.9*.7z
          ./bin/binarycreator.exe --offline-only -c config/config.xml -p packages ${{ matrix.installer-name }}
          # https://qt-project.atlassian.net/browse/QTIFW-2295
          editbin /subsystem:windows ${{ matrix.installer-name }}
          7z a -tzip -r "${{ github.workspace }}"/archive/${{ env.ARCHIVE_NAME }} ${{ matrix.installer-name }}
        elif [ "${{ matrix.build }}" = "macos-arm64" ]; then
          cd installer
          curl -k -O -L https://download.qt.io/online/qtsdkrepository/mac_x64/ifw/tools_ifw_411/qt.tools.ifw.411/4.11.0-0-202603311245ifw-mac-universal.7z
          7z x -y 4.11*.7z
          cd ../out/bin
          macdeployqt AnyLink.app
          IDENTITY=$(security find-identity -v -p codesigning | grep "Developer ID Application" | awk -F\" 'NR==1 {print $2}')
          echo $IDENTITY
          codesign --deep --force --sign "$IDENTITY" AnyLink.app
          curl -k -L -O https://github.com/tlslink/sslcon/releases/download/latest/sslcon-macOS-arm64.tar.gz
          tar -zxvf sslcon-*.tar.gz
          cp vpnagent sslcon AnyLink.app/Contents/MacOS
          mkdir -p ../../installer/packages/root/data
          mkdir -p ../../installer/packages/maintenance/data
          ../../installer/bin/archivegen ../../installer/packages/root/data/anylink.7z ./AnyLink.app
          cd ../../installer
          ./bin/binarycreator -f -c config/config.xml -p packages --mt
          lipo uninstall.app/Contents/MacOS/uninstall -remove x86_64 -output uninstall.app/Contents/MacOS/uninstall
          codesign --deep --force --sign "$IDENTITY" uninstall.app
          ./bin/archivegen ./packages/maintenance/data/uninstall.7z ./uninstall.app
          ./bin/binarycreator -f -c config/config.xml -p packages ${{ matrix.installer-name }}
          lipo ${{ matrix.installer-name }}.app/Contents/MacOS/${{ matrix.installer-name }} -remove x86_64 -output ${{ matrix.installer-name }}.app/Contents/MacOS/${{ matrix.installer-name }}
          codesign --deep --force --options=runtime --sign "$IDENTITY" ${{ matrix.installer-name }}.app
          ditto -c -k --keepParent ${{ matrix.installer-name }}.app ${{ matrix.installer-name }}.zip
          xcrun notarytool submit ${{ matrix.installer-name }}.zip --apple-id ${{ secrets.APPLE_ID }} --team-id ${{ secrets.TEAM_ID }} --password ${{ secrets.APP_PASSWORD }} --wait
          xcrun stapler staple ${{ matrix.installer-name }}.app
          hdiutil create -fs HFS+ -srcfolder ${{ matrix.installer-name }}.app -format UDZO "${{ github.workspace }}"/archive/${{ env.ARCHIVE_NAME }}
        fi
        
    - if: matrix.build == 'windows'
      name: upload unsigned artifact
      id: upload-unsigned-artifact
      uses: actions/upload-artifact@v7
      with: 
        name: ${{ env.ARCHIVE }}
        path: installer/${{ matrix.installer-name }}
        
    - if: matrix.build == 'windows'
      name: submit signing request
      uses: signpath/github-action-submit-signing-request@v2
      continue-on-error: true
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 'aadf898a-69a7-45df-b8b4-27acea6a952a'
        project-slug: 'anylink-client'
        signing-policy-slug: 'test-signing'
        artifact-configuration-slug: 'initial'
        github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
        wait-for-completion: true
        output-artifact-directory: 'archive'
        skip-decompress: true
        parameters: |
          arch: "amd64"
      
    - if: startsWith(github.ref, 'refs/heads/')
      name: Continuous release
      uses: softprops/action-gh-release@v3
      with:
        name: Continuous release
        files: archive/${{ env.ARCHIVE_NAME }}
        tag_name: latest
        prerelease: true
        
    - if: startsWith(github.ref, 'refs/tags/') && (matrix.build == 'windows')
      name: Tagged release
      uses: softprops/action-gh-release@v3
      with:
        name: Release build (${{ github.ref_name }})
        body: 'See [README](https://github.com/tlslink/anylink-client) for more details.'
        files: archive/${{ env.ARCHIVE_NAME }}
        generate_release_notes: true
        
    - if: startsWith(github.ref, 'refs/tags/') && (matrix.build != 'windows')
      name: Tagged release
      uses: softprops/action-gh-release@v3
      with:
        name: Release build (${{ github.ref_name }})
        files: archive/${{ env.ARCHIVE_NAME }}
